<?php

namespace AppBundle\Repository;

/**
 * EventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventosRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllEventos(){
        return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('a')
        ->from('AppBundle:Eventos', 'a')
        ->getQuery()
        ->getResult();
    }

}
