<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiasV2Repository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Función que devuelve todas las noticias.
     *
     * @return array
     */
    public function getNoticias()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT noticias
             FROM AppBundle\Entity\NoticiasV2 noticias
             ORDER BY noticias.id desc'
        );

        return $query->getResult();
    }

}
