<?php

namespace AppBundle\Repository;

/**
 * Noticias_eventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Noticias_eventosRepository extends \Doctrine\ORM\EntityRepository
{
}
