<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Publicaciones;

/**
 * PublicacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionesRepository extends \Doctrine\ORM\EntityRepository
{


    
}
