<?php
/**
 * @User: Guillermo Boquizo Sánchez (GUBS), Rafael García Zurita (RAGZ).
 * @File: RecuperaPuntosRepository.php
 * @Updated: 2019
 * @Description: Repositorio para la gestión de la recuperación de puntos (sin definir).
 * @license http://opensource.org/licenses/gpl-license.php  GNU Public License
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RecuperaPuntosRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecuperaPuntosRepository extends EntityRepository
{
}
