<?php
/**
 * @User: Guillermo Boquizo Sánchez (GUBS), Rafael García Zurita (RAGZ).
 * @File: TipoParteRepository.php
 * @Updated: 2019
 * @Description: Repositorio para la gestión de los tipos de parte (sin definir).
 * @license http://opensource.org/licenses/gpl-license.php  GNU Public License
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoParteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoParteRepository extends EntityRepository
{
}
