<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.file.twig.extension' shared autowired service.

return $this->services['app.file.twig.extension'] = new \AppBundle\Twig\Extension\FileExtension();
