<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

$this->services['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/login$'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/recuperarPassword'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/resetPassword'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/registro$'), array(0 => 'ROLE_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin$'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CONVIVENCIA'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CONVIVENCIA'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/partes$'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CONVIVENCIA', 2 => 'ROLE_PROFESOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/parte/'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CONVIVENCIA', 2 => 'ROLE_PROFESOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/sanciones$'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CONVIVENCIA', 2 => 'ROLE_PROFESOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/sancion/'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CONVIVENCIA', 2 => 'ROLE_PROFESOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/carnet/'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CONVIVENCIA', 2 => 'ROLE_PROFESOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/noticias$'), array(0 => 'ROLE_CONVIVENCIA'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/'), array(0 => 'ROLE_USER'), NULL);

return $instance;
