<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBteszqu\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBteszqu/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBteszqu.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBteszqu\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerBteszqu\appProdDebugProjectContainer();
