<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLdlqlro\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLdlqlro/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLdlqlro.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLdlqlro\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLdlqlro\appDevDebugProjectContainer();
