<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKcwdmma\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKcwdmma/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKcwdmma.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKcwdmma\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKcwdmma\appDevDebugProjectContainer();
