<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DiarioAulaConvivencia extends \AppBundle\Entity\DiarioAulaConvivencia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'hora', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'actitud', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'trabajo', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'idProfesor', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'idSancion', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'asiste', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'recupera'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'hora', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'actitud', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'trabajo', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'idProfesor', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'idSancion', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'asiste', '' . "\0" . 'AppBundle\\Entity\\DiarioAulaConvivencia' . "\0" . 'recupera'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DiarioAulaConvivencia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setHora($hora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora', [$hora]);

        return parent::setHora($hora);
    }

    /**
     * {@inheritDoc}
     */
    public function getHora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora', []);

        return parent::getHora();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setActitud($actitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActitud', [$actitud]);

        return parent::setActitud($actitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getActitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActitud', []);

        return parent::getActitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrabajo($trabajo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrabajo', [$trabajo]);

        return parent::setTrabajo($trabajo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrabajo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrabajo', []);

        return parent::getTrabajo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProfesor($idProfesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProfesor', [$idProfesor]);

        return parent::setIdProfesor($idProfesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProfesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProfesor', []);

        return parent::getIdProfesor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSancion(\AppBundle\Entity\Sanciones $idSancion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSancion', [$idSancion]);

        return parent::setIdSancion($idSancion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSancion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSancion', []);

        return parent::getIdSancion();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsiste($asiste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsiste', [$asiste]);

        return parent::setAsiste($asiste);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsiste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsiste', []);

        return parent::getAsiste();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecupera($recupera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecupera', [$recupera]);

        return parent::setRecupera($recupera);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecupera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecupera', []);

        return parent::getRecupera();
    }

}
