<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partes extends \AppBundle\Entity\Partes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'tareas', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'horaSalidaAula', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'horaLlegadaJefatura', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'formato', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'puntos', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idEstado', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idTipo', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idAlumno', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idProfesor', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idConducta', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'recupera', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'fechaConfirmacion', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'fechaComunicacion', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'sancion'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'tareas', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'horaSalidaAula', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'horaLlegadaJefatura', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'formato', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'observacion', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'puntos', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idEstado', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idTipo', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idAlumno', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idProfesor', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'idConducta', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'recupera', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'fechaConfirmacion', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'fechaComunicacion', '' . "\0" . 'AppBundle\\Entity\\Partes' . "\0" . 'sancion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Partes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTareas($tareas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTareas', [$tareas]);

        return parent::setTareas($tareas);
    }

    /**
     * {@inheritDoc}
     */
    public function getTareas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTareas', []);

        return parent::getTareas();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraSalidaAula($horaSalidaAula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraSalidaAula', [$horaSalidaAula]);

        return parent::setHoraSalidaAula($horaSalidaAula);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraSalidaAula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraSalidaAula', []);

        return parent::getHoraSalidaAula();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraLlegadaJefatura($horaLlegadaJefatura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraLlegadaJefatura', [$horaLlegadaJefatura]);

        return parent::setHoraLlegadaJefatura($horaLlegadaJefatura);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraLlegadaJefatura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraLlegadaJefatura', []);

        return parent::getHoraLlegadaJefatura();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormato($formato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormato', [$formato]);

        return parent::setFormato($formato);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormato', []);

        return parent::getFormato();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuntos($puntos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuntos', [$puntos]);

        return parent::setPuntos($puntos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuntos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuntos', []);

        return parent::getPuntos();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstado', []);

        return parent::getIdEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstado($idEstado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstado', [$idEstado]);

        return parent::setIdEstado($idEstado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTipo', []);

        return parent::getIdTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTipo($idTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTipo', [$idTipo]);

        return parent::setIdTipo($idTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAlumno($idAlumno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAlumno', [$idAlumno]);

        return parent::setIdAlumno($idAlumno);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAlumno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAlumno', []);

        return parent::getIdAlumno();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProfesor($idProfesor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProfesor', [$idProfesor]);

        return parent::setIdProfesor($idProfesor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProfesor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProfesor', []);

        return parent::getIdProfesor();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdConductum(\AppBundle\Entity\Conductas $idConductum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdConductum', [$idConductum]);

        return parent::addIdConductum($idConductum);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdConductum(\AppBundle\Entity\Conductas $idConductum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdConductum', [$idConductum]);

        return parent::removeIdConductum($idConductum);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdConducta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdConducta', []);

        return parent::getIdConducta();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecupera($recupera)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecupera', [$recupera]);

        return parent::setRecupera($recupera);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecupera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecupera', []);

        return parent::getRecupera();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaConfirmacion($fechaConfirmacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaConfirmacion', [$fechaConfirmacion]);

        return parent::setFechaConfirmacion($fechaConfirmacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaConfirmacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaConfirmacion', []);

        return parent::getFechaConfirmacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaComunicacion($fechaComunicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaComunicacion', [$fechaComunicacion]);

        return parent::setFechaComunicacion($fechaComunicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaComunicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaComunicacion', []);

        return parent::getFechaComunicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function addSancion(\AppBundle\Entity\Sanciones $sancion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSancion', [$sancion]);

        return parent::addSancion($sancion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSancion(\AppBundle\Entity\Sanciones $sancion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSancion', [$sancion]);

        return parent::removeSancion($sancion);
    }

    /**
     * {@inheritDoc}
     */
    public function getSancion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSancion', []);

        return parent::getSancion();
    }

}
